#!/bin/bash
export CC="gcc"
export CFLAGS="-O2 -Wall -fvisibility=hidden -flt"
if [ -f Makefile ]; then
	sudo make --silent clean
	sudo /usr/local/php5/bin/phpize --silent --clean
fi
sudo /usr/local/php5/bin/phpize --clean
sudo /usr/local/php5/bin/phpize 
sudo ./configure --enable-fastorm --with-php-config=/usr/local/php5/bin/php-config
sudo make && sudo make install
