fastorm.lo: /Users/davidmenger/Development/fastorm/ext/fastorm.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm.c -o fastorm.lo 
kernel/main.lo: /Users/davidmenger/Development/fastorm/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /Users/davidmenger/Development/fastorm/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /Users/davidmenger/Development/fastorm/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /Users/davidmenger/Development/fastorm/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /Users/davidmenger/Development/fastorm/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /Users/davidmenger/Development/fastorm/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /Users/davidmenger/Development/fastorm/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /Users/davidmenger/Development/fastorm/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /Users/davidmenger/Development/fastorm/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /Users/davidmenger/Development/fastorm/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /Users/davidmenger/Development/fastorm/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /Users/davidmenger/Development/fastorm/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /Users/davidmenger/Development/fastorm/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /Users/davidmenger/Development/fastorm/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/operators.c -o kernel/operators.lo 
kernel/concat.lo: /Users/davidmenger/Development/fastorm/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /Users/davidmenger/Development/fastorm/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /Users/davidmenger/Development/fastorm/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /Users/davidmenger/Development/fastorm/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/exit.lo: /Users/davidmenger/Development/fastorm/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/kernel/exit.c -o kernel/exit.lo 
fastorm/connectionmanager.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/connectionmanager.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/connectionmanager.zep.c -o fastorm/connectionmanager.lo 
fastorm/dataobject.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/dataobject.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/dataobject.zep.c -o fastorm/dataobject.lo 
fastorm/dbobject.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/dbobject.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/dbobject.zep.c -o fastorm/dbobject.lo 
fastorm/exception.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/exception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/exception.zep.c -o fastorm/exception.lo 
fastorm/iconnectionmanager.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/iconnectionmanager.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/iconnectionmanager.zep.c -o fastorm/iconnectionmanager.lo 
fastorm/modelmanager.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/modelmanager.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/modelmanager.zep.c -o fastorm/modelmanager.lo 
fastorm/objectmetadata.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/objectmetadata.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/objectmetadata.zep.c -o fastorm/objectmetadata.lo 
fastorm/objectquery.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/objectquery.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/objectquery.zep.c -o fastorm/objectquery.lo 
fastorm/db/columninfo.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/db/columninfo.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/db/columninfo.zep.c -o fastorm/db/columninfo.lo 
fastorm/db/connection.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/db/connection.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/db/connection.zep.c -o fastorm/db/connection.lo 
fastorm/db/dbexception.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/db/dbexception.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/db/dbexception.zep.c -o fastorm/db/dbexception.lo 
fastorm/db/drivers/mysqlidriver.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/db/drivers/mysqlidriver.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/db/drivers/mysqlidriver.zep.c -o fastorm/db/drivers/mysqlidriver.lo 
fastorm/db/event.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/db/event.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/db/event.zep.c -o fastorm/db/event.lo 
fastorm/db/iresultdriver.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/db/iresultdriver.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/db/iresultdriver.zep.c -o fastorm/db/iresultdriver.lo 
fastorm/db/query.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/db/query.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/db/query.zep.c -o fastorm/db/query.lo 
fastorm/db/result.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/db/result.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/db/result.zep.c -o fastorm/db/result.lo 
fastorm/db/resultiterator.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/db/resultiterator.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/db/resultiterator.zep.c -o fastorm/db/resultiterator.lo 
fastorm/db/translator.lo: /Users/davidmenger/Development/fastorm/ext/fastorm/db/translator.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/davidmenger/Development/fastorm/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/davidmenger/Development/fastorm/ext/fastorm/db/translator.zep.c -o fastorm/db/translator.lo 
$(phplibdir)/fastorm.la: ./fastorm.la
	$(LIBTOOL) --mode=install cp ./fastorm.la $(phplibdir)

./fastorm.la: $(shared_objects_fastorm) $(FASTORM_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_fastorm) $(FASTORM_SHARED_LIBADD)

